// <auto-generated />
using System;
using CCL.MES.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCL.MES.Infrastructure.Migrations
{
    [DbContext(typeof(MesDbContext))]
    [Migration("20260601043125_AddSpecListViewParityFields")]
    partial class AddSpecListViewParityFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CCL.MES.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ActorUsername");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.DowntimeReason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DowntimeReasons");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Drawing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CurrentVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("ProductRevisionId", "Kind", "Title")
                        .IsUnique();

                    b.ToTable("Drawings");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.DrawingApproval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("DrawingVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DrawingVersionId", "Role")
                        .IsUnique();

                    b.ToTable("DrawingApprovals");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.DrawingVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("DrawingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SupersededByVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DrawingId", "VersionNo")
                        .IsUnique();

                    b.ToTable("DrawingVersions");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.IqcInspection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<long?>("RawMaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UomQty")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber");

                    b.HasIndex("PartNo");

                    b.HasIndex("RawMaterialId");

                    b.HasIndex("ReceivedDate");

                    b.ToTable("IqcInspections");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.IqcResultDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefectCode")
                        .HasColumnType("TEXT");

                    b.Property<long>("IqcInspectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasuredValue")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IqcInspectionId");

                    b.ToTable("IqcResultDetails");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Machine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("IdealCycleTimeSec")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.ManufacturingStructure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Cavity")
                        .HasColumnType("REAL");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentPart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Effectivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectivityDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentPart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Pitch")
                        .HasColumnType("REAL");

                    b.Property<string>("Planner")
                        .HasColumnType("TEXT");

                    b.Property<double>("QtyAssembly")
                        .HasColumnType("REAL");

                    b.Property<double>("ScrapFactor")
                        .HasColumnType("REAL");

                    b.Property<double?>("ScrapPct")
                        .HasColumnType("REAL");

                    b.Property<string>("StructureType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentPart");

                    b.ToTable("ManufacturingStructures");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.ProcessCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayNameVi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Category", "Status", "DisplayOrder");

                    b.ToTable("ProcessCatalogs");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.ProductRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionLevel")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTrashed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleasedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevisionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TrashedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrashedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecCode");

                    b.HasIndex("Status");

                    b.HasIndex("ProductId", "RevisionCode")
                        .IsUnique();

                    b.ToTable("ProductRevisions");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.ProductionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DowntimeReasonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoodQty")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RejectQty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkOrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DowntimeReasonId");

                    b.HasIndex("MachineId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("ProductionLogs");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.QcCriterion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriterionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasureMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassCriteria")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceImageKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Seq")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SpecQcWindowId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TargetValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("ToleranceMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("ToleranceMin")
                        .HasColumnType("REAL");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecQcWindowId", "Seq")
                        .IsUnique();

                    b.ToTable("QcCriteria");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.QcInspection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkOrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("QcInspections");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.QcResultDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefectCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasuredValue")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pass")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QcInspectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QcInspectionId");

                    b.ToTable("QcResultDetails");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.RawMaterial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ConversionFactor")
                        .HasColumnType("REAL");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryUom")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MinimumQuantity")
                        .HasColumnType("REAL");

                    b.Property<double?>("NetWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("NetWeightUom")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextOrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<double?>("PriceInclTax")
                        .HasColumnType("REAL");

                    b.Property<string>("PriceUom")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchUom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Site")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteDescription")
                        .HasColumnType("TEXT");

                    b.Property<double?>("StandardPackSize")
                        .HasColumnType("REAL");

                    b.Property<string>("StatusCode")
                        .HasColumnType("TEXT");

                    b.Property<double?>("StdMultipleQty")
                        .HasColumnType("REAL");

                    b.Property<string>("SupplierId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SupplierLeadtimeDays")
                        .HasColumnType("REAL");

                    b.Property<string>("SupplierName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierPartDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxCodeDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartNo");

                    b.ToTable("RawMaterials");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.RoutingOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Crew")
                        .HasColumnType("REAL");

                    b.Property<string>("Effectivity")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Efficiency")
                        .HasColumnType("REAL");

                    b.Property<string>("LaborClass")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LaborRunTime")
                        .HasColumnType("REAL");

                    b.Property<double?>("LaborSetupTime")
                        .HasColumnType("REAL");

                    b.Property<double?>("MachineRunTime")
                        .HasColumnType("REAL");

                    b.Property<double?>("MachineSetupTime")
                        .HasColumnType("REAL");

                    b.Property<string>("OpNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Planner")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoutingType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SetupCrew")
                        .HasColumnType("REAL");

                    b.Property<string>("Site")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkCenterDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkCenterNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartNo");

                    b.ToTable("RoutingOperations");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecDiecut", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BleedMm")
                        .HasColumnType("REAL");

                    b.Property<string>("CncProgram")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CornerRadiusMm")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CutProcessCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("DieId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DieType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KissCutDepthUm")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LaserPowerW")
                        .HasColumnType("REAL");

                    b.Property<double?>("LengthMm")
                        .HasColumnType("REAL");

                    b.Property<string>("PerforationJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerpunchTool")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<double?>("WidthMm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProductRevisionId")
                        .IsUnique();

                    b.ToTable("SpecDiecuts");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecFinishing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CoreDiameterMm")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishingProcessesJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LabelsPerRoll")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxOuterDiaMm")
                        .HasColumnType("REAL");

                    b.Property<string>("OutputForm")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RollsPerBox")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindingDirection")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductRevisionId")
                        .IsUnique();

                    b.ToTable("SpecFinishings");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecMaterial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdhesiveBrand")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdhesiveType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinerType")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubstrateBrand")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstrateType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThicknessUm")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductRevisionId")
                        .IsUnique();

                    b.ToTable("SpecMaterials");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecPrint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cavity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorSpecJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HybridProcessesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lamination")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumColors")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PitchMm")
                        .HasColumnType("REAL");

                    b.Property<string>("ProcessCode")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Varnish")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WhiteUnderprint")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductRevisionId")
                        .IsUnique();

                    b.ToTable("SpecPrints");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecQcWindow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessCode")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SamplePlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductRevisionId", "Stage");

                    b.ToTable("SpecQcWindows");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WiStepDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningNote")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkInstructionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkInstructionId");

                    b.ToTable("WiStepDetails");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WoStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ByUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromStep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkOrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WoStatusHistories");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WorkCenter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("IdealSpeedPcsH")
                        .HasColumnType("REAL");

                    b.Property<string>("ShiftPattern")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("WorkCenters");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WorkInstruction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessStep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("WorkInstructions");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MaterialsReady")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PlannedEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProducedQty")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RohsOk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SetupConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetQty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("WoNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductRevisionId");

                    b.HasIndex("WoNo")
                        .IsUnique();

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Drawing", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.DrawingVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CCL.MES.Domain.Entities.ProductRevision", "ProductRevision")
                        .WithMany("Drawings")
                        .HasForeignKey("ProductRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentVersion");

                    b.Navigation("ProductRevision");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.DrawingApproval", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.DrawingVersion", "DrawingVersion")
                        .WithMany("Approvals")
                        .HasForeignKey("DrawingVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrawingVersion");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.DrawingVersion", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.Drawing", "Drawing")
                        .WithMany("Versions")
                        .HasForeignKey("DrawingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drawing");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.IqcInspection", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.RawMaterial", "RawMaterial")
                        .WithMany()
                        .HasForeignKey("RawMaterialId");

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.IqcResultDetail", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.IqcInspection", null)
                        .WithMany("Details")
                        .HasForeignKey("IqcInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Product", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.Customer", "Customer")
                        .WithMany("Products")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.ProductRevision", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.ProductionLog", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.DowntimeReason", "DowntimeReason")
                        .WithMany()
                        .HasForeignKey("DowntimeReasonId");

                    b.HasOne("CCL.MES.Domain.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCL.MES.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DowntimeReason");

                    b.Navigation("Machine");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.QcCriterion", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.SpecQcWindow", "SpecQcWindow")
                        .WithMany("Criteria")
                        .HasForeignKey("SpecQcWindowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecQcWindow");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.QcInspection", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Inspections")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.QcResultDetail", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.QcInspection", null)
                        .WithMany("Details")
                        .HasForeignKey("QcInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecDiecut", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.ProductRevision", "ProductRevision")
                        .WithOne("Diecut")
                        .HasForeignKey("CCL.MES.Domain.Entities.SpecDiecut", "ProductRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductRevision");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecFinishing", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.ProductRevision", "ProductRevision")
                        .WithOne("Finishing")
                        .HasForeignKey("CCL.MES.Domain.Entities.SpecFinishing", "ProductRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductRevision");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecMaterial", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.ProductRevision", "ProductRevision")
                        .WithOne("Material")
                        .HasForeignKey("CCL.MES.Domain.Entities.SpecMaterial", "ProductRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductRevision");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecPrint", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.ProductRevision", "ProductRevision")
                        .WithOne("Print")
                        .HasForeignKey("CCL.MES.Domain.Entities.SpecPrint", "ProductRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductRevision");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecQcWindow", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.ProductRevision", "ProductRevision")
                        .WithMany("QcWindows")
                        .HasForeignKey("ProductRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductRevision");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WiStepDetail", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.WorkInstruction", null)
                        .WithMany("Steps")
                        .HasForeignKey("WorkInstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WoStatusHistory", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.WorkOrder", null)
                        .WithMany("History")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WorkInstruction", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCL.MES.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCL.MES.Domain.Entities.ProductRevision", "ProductRevision")
                        .WithMany()
                        .HasForeignKey("ProductRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("ProductRevision");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Drawing", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.DrawingVersion", b =>
                {
                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.IqcInspection", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.ProductRevision", b =>
                {
                    b.Navigation("Diecut");

                    b.Navigation("Drawings");

                    b.Navigation("Finishing");

                    b.Navigation("Material");

                    b.Navigation("Print");

                    b.Navigation("QcWindows");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.QcInspection", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecQcWindow", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WorkInstruction", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WorkOrder", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
