// <auto-generated />
using System;
using CCL.MES.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCL.MES.Infrastructure.Migrations
{
    [DbContext(typeof(MesDbContext))]
    [Migration("20260531050444_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CCL.MES.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.DowntimeReason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("DowntimeReasons");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Machine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("CurrentState")
                        .IsRequired();

                    b.Property<double>("IdealCycleTimeSec");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Type");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.ManufacturingStructure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cavity");

                    b.Property<string>("Color");

                    b.Property<string>("ComponentDescription");

                    b.Property<string>("ComponentPart")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("ParentDescription");

                    b.Property<string>("ParentPart")
                        .IsRequired();

                    b.Property<string>("Pitch");

                    b.Property<double>("QtyAssembly");

                    b.Property<double>("ScrapFactor");

                    b.Property<string>("ScrapPct");

                    b.Property<string>("Uom");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("ParentPart");

                    b.ToTable("ManufacturingStructures");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<long>("CustomerId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ProductCode")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.ProductionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<long?>("DowntimeReasonId");

                    b.Property<DateTime?>("EndAt");

                    b.Property<string>("EventType")
                        .IsRequired();

                    b.Property<int>("GoodQty");

                    b.Property<long>("MachineId");

                    b.Property<string>("OperatorId");

                    b.Property<int>("RejectQty");

                    b.Property<DateTime>("StartAt");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.Property<long>("WorkOrderId");

                    b.HasKey("Id");

                    b.HasIndex("DowntimeReasonId");

                    b.HasIndex("MachineId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("ProductionLogs");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.QcInspection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ApprovedAt");

                    b.Property<string>("ApprovedBy");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("InspectorId");

                    b.Property<string>("Result")
                        .IsRequired();

                    b.Property<int>("SampleSize");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.Property<long>("WorkOrderId");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("QcInspections");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.QcResultDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("DefectCode");

                    b.Property<string>("ItemName")
                        .IsRequired();

                    b.Property<string>("MeasuredValue");

                    b.Property<bool>("Pass");

                    b.Property<long>("QcInspectionId");

                    b.Property<int>("Qty");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("QcInspectionId");

                    b.ToTable("QcResultDetails");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.RawMaterial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CatalogDesc");

                    b.Property<string>("CatalogGroup");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Currency");

                    b.Property<string>("Grp");

                    b.Property<string>("PartDescription");

                    b.Property<string>("PartNo")
                        .IsRequired();

                    b.Property<double>("Price");

                    b.Property<string>("PriceUom");

                    b.Property<string>("SupplierId");

                    b.Property<string>("SupplierName");

                    b.Property<string>("Type");

                    b.Property<string>("TypeDesc");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("PartNo");

                    b.ToTable("RawMaterials");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.RoutingOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<double>("LaborRunTime");

                    b.Property<double>("LaborSetupTime");

                    b.Property<double>("MachineRunTime");

                    b.Property<double>("MachineSetupTime");

                    b.Property<string>("OpNo");

                    b.Property<string>("Operation");

                    b.Property<string>("PartDescription");

                    b.Property<string>("PartNo")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.Property<string>("WorkCenterDescription");

                    b.Property<string>("WorkCenterNo");

                    b.HasKey("Id");

                    b.HasIndex("PartNo");

                    b.ToTable("RoutingOperations");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Spec", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<long>("ProductId");

                    b.Property<string>("SpecCode")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Specs");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecParameter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<bool>("IsCritical");

                    b.Property<string>("Nominal");

                    b.Property<string>("ParamName")
                        .IsRequired();

                    b.Property<long>("SpecVersionId");

                    b.Property<string>("TolMax");

                    b.Property<string>("TolMin");

                    b.Property<string>("Uom");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("SpecVersionId");

                    b.ToTable("SpecParameters");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ApprovedAt");

                    b.Property<string>("ApprovedBy");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("EffectiveDate");

                    b.Property<long>("SpecId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.Property<int>("VersionNo");

                    b.HasKey("Id");

                    b.HasIndex("SpecId");

                    b.ToTable("SpecVersions");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("DisplayName");

                    b.Property<DateTime?>("LastLoginAt");

                    b.Property<string>("PasswordHash")
                        .IsRequired();

                    b.Property<string>("Role")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WiStepDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("ImageUrl");

                    b.Property<int>("Sequence");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.Property<string>("WarningNote");

                    b.Property<long>("WorkInstructionId");

                    b.HasKey("Id");

                    b.HasIndex("WorkInstructionId");

                    b.ToTable("WiStepDetails");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WoStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action")
                        .IsRequired();

                    b.Property<string>("ByUser");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("FromStep")
                        .IsRequired();

                    b.Property<string>("Reason");

                    b.Property<string>("ToStep")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.Property<long>("WorkOrderId");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WoStatusHistories");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WorkCenter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Area");

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("WorkCenters");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WorkInstruction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("EffectiveDate");

                    b.Property<string>("MachineCode");

                    b.Property<string>("ProcessStep")
                        .IsRequired();

                    b.Property<long>("ProductId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.Property<int>("VersionNo");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("WorkInstructions");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("CurrentStep")
                        .IsRequired();

                    b.Property<long>("CustomerId");

                    b.Property<string>("MachineCode");

                    b.Property<string>("MachineName");

                    b.Property<bool>("MaterialsReady");

                    b.Property<DateTime?>("PlannedEnd");

                    b.Property<DateTime?>("PlannedStart");

                    b.Property<int>("Priority");

                    b.Property<int>("ProducedQty");

                    b.Property<long>("ProductId");

                    b.Property<string>("ProductName")
                        .IsRequired();

                    b.Property<bool>("RohsOk");

                    b.Property<bool>("SetupConfirmed");

                    b.Property<long?>("SpecVersionId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<int>("TargetQty");

                    b.Property<string>("Uom")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.Property<string>("WoNo")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SpecVersionId");

                    b.HasIndex("WoNo")
                        .IsUnique();

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Product", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.Customer", "Customer")
                        .WithMany("Products")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.ProductionLog", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.DowntimeReason", "DowntimeReason")
                        .WithMany()
                        .HasForeignKey("DowntimeReasonId");

                    b.HasOne("CCL.MES.Domain.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCL.MES.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DowntimeReason");

                    b.Navigation("Machine");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.QcInspection", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Inspections")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.QcResultDetail", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.QcInspection", null)
                        .WithMany("Details")
                        .HasForeignKey("QcInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Spec", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecParameter", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.SpecVersion", null)
                        .WithMany("Parameters")
                        .HasForeignKey("SpecVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecVersion", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.Spec", "Spec")
                        .WithMany("Versions")
                        .HasForeignKey("SpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spec");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WiStepDetail", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.WorkInstruction", null)
                        .WithMany("Steps")
                        .HasForeignKey("WorkInstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WoStatusHistory", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.WorkOrder", null)
                        .WithMany("History")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WorkInstruction", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("CCL.MES.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCL.MES.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCL.MES.Domain.Entities.SpecVersion", "SpecVersion")
                        .WithMany()
                        .HasForeignKey("SpecVersionId");

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("SpecVersion");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.QcInspection", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.Spec", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.SpecVersion", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WorkInstruction", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CCL.MES.Domain.Entities.WorkOrder", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
